name: "pre-release"

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [main]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Automatic Development Build"
